/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.helpdesk.view;

import br.com.helpdesk.Control.CadastraControl;
import br.com.helpdesk.Control.LonginControl;
import br.com.helpdesk.model.Usuario;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Marking
 */
public class LoginFrame extends javax.swing.JFrame {
    private LonginControl controllerLogin;
    private CadastraControl ControllerCadastro;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }
    public LoginFrame(Usuario model) {
        super("HelpDesk Shasam");
        initComponents();
        this.controllerLogin = new LonginControl(this);
        this.ControllerCadastro = new CadastraControl(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LoginPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jUserLabel = new javax.swing.JLabel();
        btEntra = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();
        CriaContaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cadastra = new javax.swing.JPanel();
        JLNome = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        txttelefone = new javax.swing.JLabel();
        jLCPF = new javax.swing.JLabel();
        JLArea = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jLConfSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBCadastra = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtAtuação = new javax.swing.JTextField();
        txtSenhaCada = new javax.swing.JPasswordField();
        txtConfSenha = new javax.swing.JPasswordField();
        jCAtende = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTecnico = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HelpDesk");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        PasswordLabel.setText("Senha: ");

        txtSenha.setText("jPasswordField1");

        jUserLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jUserLabel.setText("Login: ");

        btEntra.setText("Entra");
        btEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntraActionPerformed(evt);
            }
        });

        btCancela.setText("Cancela");
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanel2Layout = new javax.swing.GroupLayout(LoginPanel2);
        LoginPanel2.setLayout(LoginPanel2Layout);
        LoginPanel2Layout.setHorizontalGroup(
            LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanel2Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LoginPanel2Layout.createSequentialGroup()
                        .addComponent(btEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanel2Layout.createSequentialGroup()
                        .addComponent(PasswordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanel2Layout.createSequentialGroup()
                        .addComponent(jUserLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        LoginPanel2Layout.setVerticalGroup(
            LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserLabel))
                .addGap(44, 44, 44)
                .addGroup(LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(40, 40, 40)
                .addGroup(LoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntra)
                    .addComponent(btCancela))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entra", LoginPanel2);

        JLNome.setText("Nome: ");

        jLEmail.setText("E-mail:");

        txttelefone.setText("Terefone: ");

        jLCPF.setText("CPF:");

        JLArea.setText("Area de Atuação:");

        jLSenha.setText("Senha: ");

        jLConfSenha.setText("Confirma Senha:");

        jLabel1.setText("Atende Chamdo: ");

        jBCadastra.setText("Criar Conta");

        jBCancelar.setText("Cancelar");

        txtAtuação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtuaçãoActionPerformed(evt);
            }
        });

        txtSenhaCada.setText("jPasswordField1");

        txtConfSenha.setText("jPasswordField2");

        jCAtende.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel2.setText("Tecnico em:");

        javax.swing.GroupLayout CadastraLayout = new javax.swing.GroupLayout(Cadastra);
        Cadastra.setLayout(CadastraLayout);
        CadastraLayout.setHorizontalGroup(
            CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastraLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(CadastraLayout.createSequentialGroup()
                                    .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLSenha)
                                        .addComponent(jLConfSenha))
                                    .addGap(13, 13, 13)
                                    .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtConfSenha)
                                        .addComponent(txtSenhaCada))))
                            .addGroup(CadastraLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jBCadastra)
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelar)))
                        .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CadastraLayout.createSequentialGroup()
                                .addComponent(JLArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtuação, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                            .addGroup(CadastraLayout.createSequentialGroup()
                                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLNome)
                                    .addComponent(jLEmail)
                                    .addComponent(txttelefone)
                                    .addComponent(jLCPF))
                                .addGap(49, 49, 49)
                                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtCPF)))))
                    .addGroup(CadastraLayout.createSequentialGroup()
                        .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCAtende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTecnico))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        CadastraLayout.setVerticalGroup(
            CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastraLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLArea)
                    .addComponent(txtAtuação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCAtende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSenha)
                    .addComponent(txtSenhaCada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLConfSenha)
                    .addComponent(txtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastra)
                    .addComponent(jBCancelar))
                .addGap(28, 28, 28))
        );

        jScrollPane1.setViewportView(Cadastra);

        javax.swing.GroupLayout CriaContaPanelLayout = new javax.swing.GroupLayout(CriaContaPanel);
        CriaContaPanel.setLayout(CriaContaPanelLayout);
        CriaContaPanelLayout.setHorizontalGroup(
            CriaContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        CriaContaPanelLayout.setVerticalGroup(
            CriaContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriaContaPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Criar Conta", CriaContaPanel);

        jMenu1.setText("Ajuda");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Entra , Cria conta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntraActionPerformed
        
    }//GEN-LAST:event_btEntraActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelaActionPerformed

    private void txtAtuaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtuaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtuaçãoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame(new Usuario()).setVisible(true);
            }
        });
    }
    
    public String getTxtLogin() {
        return txtLogin.getText();
    }

    public void setTxtLogin(String txtLogin) {
        this.txtLogin.setText(txtLogin);
    }

    public String getTxtSenha() {
        String senha = "";
        for (int i = 0; i < txtSenha.getPassword().length; i++) {
            senha += txtSenha.getPassword()[i];
        }
        return senha;
    }

    public void setTxtSenha(String txtSenha) {
        this.txtSenha.setText(txtSenha);
    }

    public String getTxtAtuação() {
        return txtAtuação.getText();
    }

    public String getTxtCPF() {
        return txtCPF.getText();
    }

   public String getTxtConfSenha() {
        String senha = "";
        for (int i = 0; i < txtConfSenha.getPassword().length; i++) {
            senha += txtConfSenha.getPassword()[i];
        }
        return senha;
    }

    public String getTxtEmail() {
        return txtEmail.getText();
    }

    public String getTxtNome() {
        return txtNome.getText();
    }

    public String getTxtSenhaCada() {
         String senha = "";
        for (int i = 0; i < txtSenhaCada.getPassword().length; i++) {
            senha += txtSenhaCada.getPassword()[i];
        }
        return senha;
    }

    public String getTxtTelefone() {
        return txtTelefone.getText();
    }

    public String getjCAtende() {
        return (String) jCAtende.getSelectedItem();
              
    }
    
    public JComboBox pegaJCAtende(){
        return jCAtende;
    }

    public JButton getjBCadastra() {
        return jBCadastra;
    }

    public JButton getjBCancelar() {
        return jBCancelar;
    }

    public JButton getBtCancela() {
        return btCancela;
    }

    public JButton getBtEntra() {
        return btEntra;
    }

    public JTextField getTxtTecnico() {
        return txtTecnico;
    }
    
    public String pegarTxtTecnico(){
        return txtTecnico.getText();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastra;
    private javax.swing.JPanel CriaContaPanel;
    private javax.swing.JLabel JLArea;
    private javax.swing.JLabel JLNome;
    private javax.swing.JPanel LoginPanel2;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btEntra;
    private javax.swing.JButton jBCadastra;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<String> jCAtende;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLConfSenha;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jUserLabel;
    private javax.swing.JTextField txtAtuação;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JPasswordField txtConfSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaCada;
    private javax.swing.JTextField txtTecnico;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JLabel txttelefone;
    // End of variables declaration//GEN-END:variables
}
