-- MySQL Script generated by MySQL Workbench
-- Dom 11 Dez 2016 19:12:39 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema HelpDesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HelpDesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HelpDesk` ;
USE `HelpDesk` ;

-- -----------------------------------------------------
-- Table `HelpDesk`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`usuario` (
  `id` INT NOT NULL COMMENT '				\n	\n\n',
  `nome` VARCHAR(200) NULL,
  `cpf` VARCHAR(11) NULL COMMENT '		\n',
  `telefone` VARCHAR(11) NULL,
  `atende` TINYINT(1) NULL,
  `email` VARCHAR(200) NULL,
  `areaatuacao` VARCHAR(100) NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Tecnico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tecnico_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Tecnico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `HelpDesk`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Chamado` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `descrição` VARCHAR(500) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `prioridade` VARCHAR(50) NOT NULL,
  `atendido` TINYINT(1) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Chamado_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Chamado_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `HelpDesk`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`resposta` (
  `id` INT NOT NULL,
  `resposta` VARCHAR(200) NULL,
  `usuario_id` INT NOT NULL,
  `Chamado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resposta_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resposta_Chamado1_idx` (`Chamado_id` ASC),
  CONSTRAINT `fk_resposta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `HelpDesk`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resposta_Chamado1`
    FOREIGN KEY (`Chamado_id`)
    REFERENCES `HelpDesk`.`Chamado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
